# Generated by Django 3.0.2 on 2020-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0006_auto_20200110_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='example@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.IntegerField(default=0),
        ),
    ]
