# Generated by Django 3.0.2 on 2020-01-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0010_auto_20200111_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.BigIntegerField(default=0, verbose_name='Phone number'),
        ),
    ]
