# Generated by Django 3.0.2 on 2020-01-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0011_auto_20200111_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='psize_status',
            new_name='p_status',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='psize_date',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='psize_size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='p_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='p_name',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='productsize',
            name='p_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsize',
            name='p_qty',
            field=models.IntegerField(default=0),
        ),
    ]
