# Generated by Django 3.0.2 on 2020-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0013_auto_20200120_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='p_name',
            field=models.CharField(max_length=30),
        ),
    ]
