# Generated by Django 3.0.2 on 2020-01-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0014_auto_20200120_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='p_price',
            new_name='product_size',
        ),
    ]
