# Generated by Django 3.0.2 on 2020-01-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0016_auto_20200120_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='p_name',
        ),
    ]
