# Generated by Django 3.0.2 on 2020-01-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0017_remove_productsize_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='product_size',
            new_name='p_size',
        ),
    ]
