# Generated by Django 3.0.2 on 2020-01-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
