# Generated by Django 3.0.2 on 2020-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0002_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='psize_size',
            field=models.CharField(max_length=100),
        ),
    ]
