# Generated by Django 3.0.2 on 2020-01-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0003_auto_20200110_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField(blank=True)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_qty', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('product_date', models.DateTimeField(verbose_name='Date added')),
                ('product_status', models.IntegerField(default=1)),
                ('product_sizeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzapp.Productsize')),
            ],
        ),
    ]
