# Generated by Django 3.0.2 on 2020-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0007_auto_20200110_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='example', max_length=200),
        ),
    ]
