# Generated by Django 3.0.2 on 2020-01-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0008_auto_20200111_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
