# Generated by Django 3.0.2 on 2020-01-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0009_auto_20200111_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='11', max_length=200),
        ),
    ]
